foo do
if a is A do // type of 'a' is 'A'
else
end

if a is
	:A
       // statements
	:B
       // statements
		io.put ("B!")
	:C, D
       // statements
    :1 .. 2, "a" .. "z"
       // statements
else
       // statements
		io.put ("ELSE!")
end



x is 
	if a is
		:A // expression
		:B // expression
		:C, D // expression
	    :1 .. 2, "a" .. "z" // expression
	else // expression

/*
x is 
  a is C do 5 else 6


if a is
	:true
		io.put ("True")
	:false
		io.put ("False")
end
*/

/*
if expr is Type 
if expr is ?
if expr is : 
*/


end
