main do


x is 
	if a is
		:A 1 // expression
		:B 2 // expression
		:C, D 3// expression
	    :1 .. 2, "a" .. "z" 4// expression
	else 5// expression




if a is A do // type of 'a' is 'A'
else
end

if a is
	:A
       // statements
	:B
       // statements
		IO.put ("B!")
	:C, D
       // statements
    :1 .. 2, "a" .. "z"
       // statements
else
       // statements
		IO.put ("ELSE!")
end




/*
x is 
  a is C do 5 else 6


if a is
	:true
		IO.put ("True")
	:false
		IO.put ("False")
end
*/

/*
if expr is Type 
if expr is ?
if expr is : 
*/


end
